version: "2.3"
services:
  web:
    image: fave_merchants_api
    container_name: merchants_management_api
    ports:
      - 9000:9000
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./config.json:/app/config.json
  mysql:
    image: mysql:5.7 
    container_name: fave_merchants_api_mysql
    command: mysqld --user=root
    volumes:
      - ./merchants.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=fave_merchants
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
